build:
  version: "2.0"

accounts:
  message: "Welcome to eazybank accounts related prod services"
  contactDetails:
    name: "John Doe - Developer"
    email : "john@eazybank.com"
  onCallSupport:
    - (555)222-1234
    - (555)222-5678