services:

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    extends:
      file: common-config.yml
      service: network-deploy-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    ports:
      - "127.0.0.1:7080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: sidharth3006/configserver:s13
    container_name: configserver-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      OTEL_SERVICE_NAME: loans

  eurekaserver:
    image: sidharth3006/eurekaserver:s13
    container_name: eurekaserver-ms
    ports:
      - 8070:8070
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      OTEL_SERVICE_NAME: eurekaserver

  accounts:
    image: sidharth3006/accounts:s13
    container_name: accounts-ms
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      rabbit:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accounts
      OTEL_SERVICE_NAME: accounts
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: sidharth3006/loans:s13
    container_name: loans-ms
    healthcheck:
      test: "curl --fail --silent http://localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loans
      OTEL_SERVICE_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: sidharth3006/cards:s13
    container_name: cards-ms
    healthcheck:
      test: "curl --fail --silent http://localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cards
      OTEL_SERVICE_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: sidharth3006/gatewayserver:s13
    container_name: gatewayserver-ms
    ports:
      - 8072:8072
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      OTEL_SERVICE_NAME: gatewayserver
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  message:
    image: "eazybytes/message:s13"
    container_name: message-ms
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: network-deploy-service
networks:
  banking-network:
    driver: bridge
